---
##
# Important variables
##
# Project
ha_mode: "no"
project_name: onap_test

# Network
public_network_name: ext-net
oam_network_cidr: 192.168.12.0/24

# Images
default_image: debian-9
default_user: debian
## Used for legacy, will be removed soon
ubuntu_16_04_image: ubuntu-14.04-daily
ubuntu_14_04_image: ubuntu-16.04-daily
centos_7_image: centos-7

# Access
pub_key_path: "{{ ansible_user_dir }}/.ssh/id_rsa.pub"
openstack_horizon_url: https://osa.pod4.opnfv.fr/

# DNSaas
# If set to yes, use multicloud DNSaaS service.
# If set to no, use the designate present on the Openstack cloud.
dns_list:
  - 10.4.0.15
  - 10.4.0.16
dnsaas_config_enabled: "no"
# give the dcae domain where we should register our VMs
dcae_domain: onap.bzh
# Put the public and secret key to be used by DCAE
dcae_public_key_path: "{{ ansible_user_dir }}/.ssh/id_rsa.pub"
dcae_private_key_path: "{{ ansible_user_dir }}/.ssh/id_rsa"

# Today's ONAP install is just able to deploy on the same openstack
dnsaas_region: "{{ openstack_region }}"
dnsaas_keystone_url: "{{ openstack_keystone_url }}"
dnsaas_tenant_name: "{{ openstack_tenant_name }}"
dnsaas_username: "{{ openstack_username }}"
dnsaas_password: "{{ openstack_api_key }}"

# Put the multivim provided keystone API url here
# if using multicoud DNSaas Service
dcae_keystone_url: PUT THE MULTIVIM PROVIDED KEYSTONE API URL HERE

##
# check if variables check your
# environment
##
flavor_small: onap.small
flavor_medium: onap.medium
flavor_large: onap.large
flavor_xlarge: onap.xlarge
flavor_xxlarge: onap.xxlarge

##
# Other variables
##
default_volume_size: 40
use_vm_base_name: "no"
vm_base_name: onap
# We start at 50 for DHCP in order to leave space for the HEAT part
subnet_pool_start: 50
subnet_pool_end: 200
key_name: "{{ project_name }}"
heat_stack_name: "{{ project_name }}"
onap_etc_path: "/opt/{{ project_name }}"
oam_network_name: "{{ project_name }}"
oam_subnet_name: "{{ oam_network_name }}-subnet"
oam_router_name: "{{ oam_network_name }}"
security_group_name: "{{ project_name }}"

enable_aai: "yes"
enable_appc: "yes"
enable_dcae: "yes"
enable_dns: "yes"
enable_consul: "yes"
enable_so: "yes"
enable_mr: "yes"
enable_policy": "yes"
enable_portal: "yes"
enable_robot: "yes"
enable_sdc: "yes"
enable_sdnc: "yes"
enable_vid: "yes"
enable_clamp: "yes"
enable_openo: "yes"

virtual_machines:
  vid:
    vm_number: 1
    short_name: vid
    flavor: "{{ flavor_medium }}"
    volumes:
      - name: default
        # If name is set to default, the naming will be 
        # 'vm_name-volume_number-vm_number'
        size: "{{ default_volume_size }}"
    groups:
      - server
      - docker
      - private_docker
      - git
      - volume
    ip_addr_fact: vid_ip_addr

##
# Don't touch unless you know what to do
##
consul_vm_numbers: "{{ (ha_mode | bool) | ternary(3,1) }}"

# Either use these variables or source an openstack rc file
# openstack_tenant_id:
openstack_tenant_name: "{{ project_name }}"
# openstack_username:
# openstack_api_key:
openstack_auth_method: password
# openstack_region:
# openstack_keystone_url:

# If you don't want a component, put the value to false

# If left commented, addresses will be chosen automatically
# aai1_ip_addr:
# aai2_ip_addr:
# appc_ip_addr:
# dcae_ip_addr:
# dns_ip_addr:
# so_ip_addr:
# mr_ip_addr:
# policy_ip_addr:
# portal_ip_addr:
# robot_ip_addr:
# sdc_ip_addr:
# sdnc_ip_addr:
# vid_ip_addr:
# clamp_ip_addr:
# openo_ip_addr:

nexus_repo: https://nexus.onap.org/content/sites/raw
nexus_docker_repo: nexus3.onap.org:10001
# fill it if you want to retrieve the images of "default" docker from
# different repo than docker hub.
# default_docker_repo:
nexus_username: docker
nexus_password: docker
dmaap_topic: AUTO
artifacts_version: 1.2.0-SNAPSHOT
cloud_env: openstack

aai_branch: master
appc_branch: master
so_branch: master
mr_branch: master
policy_branch: master
portal_branch: master
robot_branch: master
sdc_branch: master
sdnc_branch: master
clamp_branch: master
vnfsdk_branch: master

aai_docker: v1.1.0
aai_sparky_docker: v1.1.0
appc_docker: v1.2.0
so_docker: v1.1.1
dcae_docker: v1.1.0
policy_docker: v1.1.1
portal_docker: v1.3.0
robot_docker: 1.1-STAGING-latest
sdc_docker: v1.1.0
sdnc_docker: v1.2.1
clamp_docker: v1.1.0
msb_docker: 1.0.0
mvim_docker: v1.0.0
uui_docker: v1.0.1
esr_docker: v1.0.0
dgbuilder_docker: v0.1.0
cli_docker: v1.1.0

vfc_nokia_docker: v1.0.2
vfc_ztevmanagerdriver_docker: v1.0.2
vfc_ztesdncdriver_docker: v1.0.0
vfc_vnfres_docker: v1.0.1
vfc_vnfmgr_docker: v1.0.1
vfc_vnflcm_docker: v1.0.1
vfc_resmanagement_docker: v1.0.0
vfc_nslcm_docker: v1.0.2
vfc_huawei_docker: v1.0.2
vfc_jujudriver_docker: v1.0.0
vfc_gvnfmdriver_docker: v1.0.1
vfc_emsdriver_docker: v1.0.1
vfc_catalog_docker: v1.0.2
vfc_wfengine_mgrservice_docker: v1.0.0
vfc_wfengine_activiti_docker: v1.0.0

aai_repo: http://gerrit.onap.org/r/aai/test-config
appc_repo: http://gerrit.onap.org/r/appc/deployment.git
mr_repo: http://gerrit.onap.org/r/dcae/demo/startup/message-router.git
so_repo: http://gerrit.onap.org/r/so/docker-config.git
policy_repo: http://gerrit.onap.org/r/policy/docker.git
portal_repo: http://gerrit.onap.org/r/portal.git
robot_repo: http://gerrit.onap.org/r/testsuite/properties.git
sdc_repo: http://gerrit.onap.org/r/sdc.git
sdnc_repo: http://gerrit.onap.org/r/sdnc/oam.git

clamp_repo: http://gerrit.onap.org/r/clamp.git
vnfsdk_repo: http://gerrit.onap.org/r/vnfsdk/refrepo.git


maria_image: mariadb
maria_version: 10
