---
onap_module_name: clamp

clamp_repo_path: "{{ onap_etc_path }}/{{ onap_module_name }}"


clamp_container_name: clamp
clamp_docker_image: onap/clamp
clamp_version: v1.1.0
clamp_port: 8080
clamp_volume: "{{ clamp_repo_path }}/extra/docker/clamp/config/"
clamp_env: "{{clamp_repo_path}}/extra/docker/clamp/clamp.env"

clamp_maria_name: clamp_db
clamp_maria_version: 10.1.11
clamp_maria_port: 3306
volume_location: "{{ onap_etc_path }}/{{ onap_module_name }}/data-maria"
clamp_maria_conf_volume: "{{ clamp_repo_path }}/extra/docker/mariadb/conf1"
clamp_maria_sql_volume: "{{ clamp_repo_path }}/extra/sql"
# harcoded password .. you can change it but then you must adapt the sql scripts
clamp_db_root_password: DHsqJH+g*!uyG46gujz

volume_locations:
  - "{{ volume_location }}"

containers:
  - "{{ default_docker_repo }}{{ maria_image }}:{{ clamp_maria_version }}"
  - "{{ nexus_docker_repo }}/{{ clamp_docker_image }}:{{ clamp_version }}"
