---
stages:
  - test
  # - deploy

.syntax_checking: &syntax_docker
  stage: test
  tags:
    - shared
    - docker
    - innovation

yaml_checking:
  image: dockerproxy-iva.si.francetelecom.fr/sdesbure/yamllint:latest
  script:
    - yamllint .gitlab-ci.yml
    - yamllint *.yml
    - yamllint vars/*.yml
  <<: *syntax_docker

ansible_linting:
  image: dockerproxy-iva.si.francetelecom.fr/sdesbure/ansible-lint:latest
  script:
    - ansible-lint -x ANSIBLE0010,ANSIBLE0013 onap-*.yml
  <<: *syntax_docker

# pages:
#   stage: deploy
#   image: dockerproxy-iva.si.francetelecom.fr/jekyll/jekyll:latest
#   tags:
#     - shared
#     - innovation
#     - docker
#   script:
#     - cd doc
#     - jekyll build -d ../public
#   only:
#     - master
#   artifacts:
#     paths:
#       - public
#
# build_markdown:
#   stage: build
#   image: dockerproxy-iva.si.francetelecom.fr/williamyeh/ansible:alpine3
#   tags:
#     - shared
#     - innovation
#     - docker
#   only:
#     - master
#   script:
#     - cd doc
#     - ansible-playbook build_markdown.yml
#   artifacts:
#     paths:
#       - doc/_pods
#       - doc/nodes.md
